server:
  port: 12000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.187.212:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  redis:
    host: 47.98.187.212
  session:
    store-type: redis
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  #采样取值介于 0到1之间，1则表示全部收集
  sleuth:
    sampler:
      probability: 1
logging:
  level:
    io.niceseason.gulimall.search.service: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'